### ISSUE TITLE
Cannot launch 

### ISSUE THREAD

**Issue by domhof** [radixdlt/radixdlt-core#35]
I keep getting the following error when trying to launch a node with `docker-compose -f docker/single-node.yml up --build`:

`Building core
Step 1/11 : FROM eu.gcr.io/lunar-arc-236318/base-core
ERROR: Service 'core' failed to build: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
`

Any advice on how to fix this?

**Comment by clstrfsck** [comment]
Looks like our base-core image is in our private repo.  We need to move to dockerhub.  Bear with us while we sort this out.

**Comment by clstrfsck** [comment]
@domhof , Hotfix has been pushed to hotfix/public-docker-repo at https://github.com/radixdlt/radixdlt-core/tree/hotfix/public-docker-repo

If you have some spare time, feel free to try on this branch.  I would expect this to be merged to release once #38 passes review in the next day or so.

**Comment by clstrfsck** [comment]
Hotfix merged onto release/1.0-beta.6 branch.

**Comment by domhof** [comment]
It's working. :-) Thanks @clstrfsck!
